//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ncl.assisted_search.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.ncl.assisted_search.messages.GetAssistedSearchRecommendation;
import com.ncl.assisted_search.messages.GetAssistedSearchRecommendationResponse;
import com.ncl.assisted_search.messages.ObjectFactory;

@WebService(name = "AssistedSearchServicesPortType", targetNamespace = "http://assisted-search.ncl.com/services/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AssistedSearchServicesPortType {


    /**
     * 
     * @param getAssistedSearchRecommendation
     * @return
     *     returns com.ncl.assisted_search.messages.GetAssistedSearchRecommendationResponse
     */
    @WebMethod(operationName = "GetAssistedSearchRecommendations", action = "http://assisted-search.ncl.com/services/AssistedSearchServices/GetAssistedSearchRecommendations")
    @WebResult(name = "GetAssistedSearchRecommendationResponse", targetNamespace = "http://assisted-search.ncl.com/messages", partName = "GetAssistedSearchRecommendationResponse")
    public GetAssistedSearchRecommendationResponse getAssistedSearchRecommendations(
        @WebParam(name = "GetAssistedSearchRecommendation", targetNamespace = "http://assisted-search.ncl.com/messages", partName = "GetAssistedSearchRecommendation")
        GetAssistedSearchRecommendation getAssistedSearchRecommendation);

}
